// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeCR7JhkLbLsgLXrMJ0Q9R-eku0lCT88M',
    appId: '1:156278743922:web:4be68a300d564fe85533eb',
    messagingSenderId: '156278743922',
    projectId: 'digicalendar-c34fb',
    authDomain: 'digicalendar-c34fb.firebaseapp.com',
    storageBucket: 'digicalendar-c34fb.firebasestorage.app',
    measurementId: 'G-VMR5L16CKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmb3tPty97gFSorOpLU98VdZNyIl6Tb8',
    appId: '1:156278743922:android:e267200eaeb357ee5533eb',
    messagingSenderId: '156278743922',
    projectId: 'digicalendar-c34fb',
    storageBucket: 'digicalendar-c34fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqf3gkOD_Y_L0OI9p3PppHJhVytb3N2w',
    appId: '1:156278743922:ios:6870227baa22cf675533eb',
    messagingSenderId: '156278743922',
    projectId: 'digicalendar-c34fb',
    storageBucket: 'digicalendar-c34fb.firebasestorage.app',
    iosBundleId: 'inc.seven.digicalendar.digiCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqf3gkOD_Y_L0OI9p3PppHJhVytb3N2w',
    appId: '1:156278743922:ios:6870227baa22cf675533eb',
    messagingSenderId: '156278743922',
    projectId: 'digicalendar-c34fb',
    storageBucket: 'digicalendar-c34fb.firebasestorage.app',
    iosBundleId: 'inc.seven.digicalendar.digiCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeCR7JhkLbLsgLXrMJ0Q9R-eku0lCT88M',
    appId: '1:156278743922:web:c2c0ea7af51a533b5533eb',
    messagingSenderId: '156278743922',
    projectId: 'digicalendar-c34fb',
    authDomain: 'digicalendar-c34fb.firebaseapp.com',
    storageBucket: 'digicalendar-c34fb.firebasestorage.app',
    measurementId: 'G-060QCBF4K3',
  );
}
